package com.grassland.identity.organization.subaccount;

import static org.assertj.core.api.Assertions.assertThat;

import com.grassland.identity.IdentityItSupport;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;

/**
 * 子账号体系端到端（任务书 #48；#49 loginName 改造）。继承 {@link IdentityItSupport}，
 * 共享容器数据按登录名前缀隔离。
 *
 * <p>覆盖矩阵（#52 池模型后）：直建 happy path（入池+挂店+前缀拼接/旁表/占位邮箱）、
 * 撞登录名 409、格式校验 4xx、审核流退役（三端点 404 + 直建恒 active）、三守卫
 * （owner 自保护/自操作）、一店一店长建号闸、纯门店经理权限边界、删除终态、前缀读端点。
 * D8①「最后店长不可停/删」已废除（#52 决策 E），分配/移除/调度端点见 StoreAssignmentIT。
 */
class OrgSubAccountControllerIT extends IdentityItSupport {

    // ---------- 建号（loginName 契约） ----------

    @Test
    void createManager_subaccountActiveWithUsernameAndOneTimePassword() {
        var owner = seedAccount("sa-owner4@example.com");
        String orgId = createOrg(owner.cookie(), "直建主体");
        String storeId = createStore(orgId, owner.cookie(), "旗舰店");

        Map<String, Object> data = createAccount(orgId, owner.cookie(),
                "{\"role\":\"manager\",\"storeId\":\"" + storeId + "\",\"loginName\":\"mgr4\","
                        + "\"displayName\":\"王经理\"}")
                .expectStatus().isCreated()
                .expectBody(Map.class).returnResult().getResponseBody();
        // expectBody(Map) 拿到的是整包 {success,data}；业务体在 data 键下
        data = (Map<String, Object>) data.get("data");
        String accountId = (String) ((Map<?, ?>) data.get("account")).get("id");

        assertThat(((Map<?, ?>) data.get("account")).get("status")).isEqualTo("active");
        assertThat((String) data.get("initialPassword")).hasSize(16);

        // #49：账号名 = 主体前缀-登录名；email 列是占位符（.invalid 域）；旁表有登录名行
        String prefix = accountPrefix(orgId);
        assertThat(((Map<?, ?>) data.get("account")).get("username")).isEqualTo(prefix + "-mgr4");
        String email = db.sql("SELECT email FROM app_users WHERE id = CAST(:id AS uuid)")
                .bind("id", accountId).map(r -> r.get("email", String.class)).one().block();
        assertThat(email).isEqualTo(prefix + "-mgr4@sub.grassland.invalid");
        String usernameRow = db.sql("SELECT username FROM account_username WHERE account_id = CAST(:id AS uuid)")
                .bind("id", accountId).map(r -> r.get("username", String.class)).one().block();
        assertThat(usernameRow).isEqualTo(prefix + "-mgr4");

        Boolean flagged = db.sql(
                        "SELECT must_change_password FROM account_flag WHERE account_id = CAST(:id AS uuid)")
                .bind("id", accountId)
                .map(r -> r.get("must_change_password", Boolean.class)).one().block();
        assertThat(flagged).isTrue();

        Long events = db.sql("SELECT COUNT(*)::int AS c FROM outbox"
                        + " WHERE event_type = 'OrgSubAccountCreated'"
                        + " AND payload->>'organizationId' = :org")
                .bind("org", orgId)
                .map(r -> r.get("c", Integer.class)).one().block().longValue();
        assertThat(events).isGreaterThanOrEqualTo(1);
    }

    @Test
    void duplicateLoginName_rejected409_andFormatValidated() {
        var owner = seedAccount("sa-dup@example.com");
        String orgId = createOrg(owner.cookie(), "撞名主体");
        String storeId = createStore(orgId, owner.cookie(), "撞名店");

        createAccount(orgId, owner.cookie(), staffJson(storeId, "dup1", "先来"))
                .expectStatus().isCreated();

        // 同主体同名 → 409 换名（占位邮箱 UNIQUE 与旁表 UNIQUE 双闸）
        createAccount(orgId, owner.cookie(), staffJson(storeId, "dup1", "后到"))
                .expectStatus().isEqualTo(409)
                .expectBody().jsonPath("$.error").isEqualTo("该登录名已被使用，请换一个");

        // 格式：过短 / 非法字符 / 缺失
        createAccount(orgId, owner.cookie(), staffJson(storeId, "ab", "过短"))
                .expectStatus().isBadRequest();
        createAccount(orgId, owner.cookie(), staffJson(storeId, "bad_name", "下划线非法"))
                .expectStatus().isBadRequest();
        createAccount(orgId, owner.cookie(),
                "{\"role\":\"staff\",\"storeId\":\"" + storeId + "\",\"loginName\":\"okname\","
                        + "\"displayName\":\"缺登录名对照\"}")
                .expectStatus().isCreated();
    }

    /**
     * 前缀读端点（建号表单预览）。任务书 #51：商家侧改前缀（PATCH）已删除并收归运营
     * （{@code PATCH /api/admin/organizations/{id}/account-prefix}），改名语义与连带重写的覆盖
     * 移至 {@code OrganizationPrefixAdminIT}；此处只保留「自动生成 + 成员可读 + 非成员不可读」。
     */
    @Test
    void accountPrefix_autoGenerated_readableByMember_notByOutsider() {
        var owner = seedAccount("sa-prefix@example.com");
        String orgId = createOrg(owner.cookie(), "前缀主体");

        // 建主体即生成默认前缀（org + id 前 8 位 hex，V43 同规则）——商家无需也无法自选
        String generated = accountPrefix(orgId);
        assertThat(generated).matches("^org[0-9a-f]{8}$");

        // 商家侧改前缀入口已不存在（该路径只剩 GET）
        client().patch().uri("/api/organizations/" + orgId + "/account-prefix")
                .contentType(MediaType.APPLICATION_JSON).header("Cookie", "y1.sid=" + owner.cookie())
                .bodyValue("{\"prefix\":\"milkshop\"}")
                .exchange().expectStatus().isEqualTo(405);
        assertThat(accountPrefix(orgId)).isEqualTo(generated);

        // 成员可读（建号表单预览）；非成员 403
        var member = seedAccount("sa-prefix-mem@example.com");
        seedOrgRole(orgId, member.accountId(), "member");
        client().get().uri("/api/organizations/" + orgId + "/account-prefix")
                .header("Cookie", "y1.sid=" + member.cookie()).exchange()
                .expectStatus().isOk().expectBody().jsonPath("$.data.prefix").isEqualTo(generated);
        var outsider = seedAccount("sa-prefix-out@example.com");
        client().get().uri("/api/organizations/" + orgId + "/account-prefix")
                .header("Cookie", "y1.sid=" + outsider.cookie()).exchange()
                .expectStatus().isForbidden();
    }

    // ---------- 审核流退役（#52 决策 A） ----------

    @Test
    void reviewFlowRetired_endpointsGone_creationAlwaysActive() {
        var owner = seedAccount("sa-review@example.com");
        String cookie = owner.cookie();
        String orgId = createOrg(cookie, "审核主体");
        String storeId = createStore(orgId, cookie, "分店A");

        // 三条退役路径一律 404（端点已删，不再有 pending 产生通路）
        client().patch().uri("/api/organizations/" + orgId + "/member-review-required")
                .contentType(MediaType.APPLICATION_JSON).header("Cookie", "y1.sid=" + cookie)
                .bodyValue("{}").exchange().expectStatus().isNotFound();
        client().get().uri("/api/organizations/" + orgId + "/member-review-required")
                .header("Cookie", "y1.sid=" + cookie).exchange().expectStatus().isNotFound();
        client().post().uri("/api/organizations/" + orgId + "/stores/" + storeId + "/accounts")
                .contentType(MediaType.APPLICATION_JSON).header("Cookie", "y1.sid=" + cookie)
                .bodyValue("{}").exchange().expectStatus().isNotFound();
        client().post().uri("/api/organizations/" + orgId + "/accounts/00000000-0000-0000-0000-000000000000/review")
                .contentType(MediaType.APPLICATION_JSON).header("Cookie", "y1.sid=" + cookie)
                .bodyValue("{}").exchange().expectStatus().isNotFound();

        // 唯一建号路径（主体直建）恒 active；列表带账号状态（读侧契约保留）
        Map<String, Object> offCase = createAccount(orgId, cookie,
                staffJson(storeId, "instant7", "即启用员工"))
                .expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();
        offCase = (Map<String, Object>) offCase.get("data");
        assertThat(((Map<?, ?>) offCase.get("account")).get("status")).isEqualTo("active");

        client().get().uri("/api/organizations/" + orgId + "/stores/" + storeId + "/memberships")
                .header("Cookie", "y1.sid=" + cookie).exchange()
                .expectStatus().isOk().expectBody()
                .jsonPath("$.data[?(@.role=='staff')].accountStatus").isEqualTo("active");
    }

    // ---------- 四守卫 ----------

    @Test
    void guard_selfOperation_and_ownerProtection() {
        var owner = seedAccount("sa-guard@example.com");
        String orgId = createOrg(owner.cookie(), "守卫主体");

        // ③ 自操作拒绝
        suspend(orgId, owner.accountId(), owner.cookie()).expectStatus().isForbidden();

        // ② OWNER 账号不可被其他管理员停用
        var secondAdmin = seedAccount("sa-guard-admin@example.com");
        seedOrgRole(orgId, secondAdmin.accountId(), "admin");
        suspend(orgId, owner.accountId(), secondAdmin.cookie()).expectStatus().isForbidden()
                .expectBody().jsonPath("$.error").isEqualTo("商家主体所有者的账号不可被停用");
    }

    @Test
    void uniqueManagerGate_and_suspendingSoleManagerAllowed() {
        var owner = seedAccount("sa-lastmgr@example.com");
        String cookie = owner.cookie();
        String orgId = createOrg(cookie, "末位经理主体");
        String storeId = createStore(orgId, cookie, "独苗店");

        Map<String, Object> mgr = createAccount(orgId, cookie,
                managerJson(storeId, "onlymgr", "唯一经理"))
                .expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();
        mgr = (Map<String, Object>) mgr.get("data");
        String mgrId = (String) ((Map<?, ?>) mgr.get("account")).get("id");

        // 决策 B（建号闸）：同店再建第二位店长 → 409，一店一店长
        createAccount(orgId, cookie, managerJson(storeId, "backupmgr", "替补经理"))
                .expectStatus().isEqualTo(409)
                .expectBody().jsonPath("$.error").isEqualTo("该门店已有店长，请先移除或调度原店长");

        // 决策 E：D8① 已废除——停用唯一店长成功，店进入「主体代管」态
        suspend(orgId, mgrId, cookie).expectStatus().isOk();
        assertThat(statusOf(mgrId)).isEqualTo("suspended");

        restore(orgId, mgrId, cookie).expectStatus().isOk();
        assertThat(statusOf(mgrId)).isEqualTo("active");
        restore(orgId, mgrId, cookie).expectStatus().isEqualTo(409);
    }

    // ---------- 纯门店经理权限边界 ----------

    @Test
    void storeManager_canManageOwnStaff_butForeignAccountsAre404() {
        var owner = seedAccount("sa-bnd@example.com");
        String cookie = owner.cookie();
        String orgId = createOrg(cookie, "边界主体");
        String storeId = createStore(orgId, cookie, "边界店");

        var manager = createManagerViaOrg(orgId, storeId, cookie, "bndmgr", "边界店长");
        var outsider = seedAccount("sa-bnd-out@example.com");

        // #52：店长不再自建——员工由主体直建入池挂店，店长只有停用/恢复权
        Map<String, Object> staff = createAccount(orgId, cookie, staffJson(storeId, "bndstaff", "受管员工"))
                .expectStatus().isCreated()
                .expectBody(Map.class).returnResult().getResponseBody();
        staff = (Map<String, Object>) staff.get("data");
        String staffId = (String) ((Map<?, ?>) staff.get("account")).get("id");

        // 店长可停用本店员工（免审默认）
        suspend(orgId, staffId, manager.cookie()).expectStatus().isOk();
        assertThat(statusOf(staffId)).isEqualTo("suspended");

        // 恢复本店员工也由店长直接操作（用户拍板②）
        restore(orgId, staffId, manager.cookie()).expectStatus().isOk();

        // 对组织外的账号 → 404 跨主体隔离
        suspend(orgId, outsider.accountId(), manager.cookie()).expectStatus().isNotFound();
    }

    // ---------- 删除（任务书 #49 D8：永久作废 + 逻辑删除留痕）----------

    @Test
    void deleteSubAccount_relationsCleared_statusDeletedWithTrace_restoreRejected() {
        var owner = seedAccount("sa-del@example.com");
        String cookie = owner.cookie();
        String orgId = createOrg(cookie, "删除主体");
        String storeId = createStore(orgId, cookie, "删除店");

        Map<String, Object> staff = createAccount(orgId, cookie, staffJson(storeId, "delstaff", "将被删"))
                .expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();
        String staffId = (String) ((Map<?, ?>) ((Map<?, ?>) staff.get("data")).get("account")).get("id");

        client().delete().uri("/api/organizations/" + orgId + "/accounts/" + staffId)
                .header("Cookie", "y1.sid=" + cookie).exchange().expectStatus().isOk();

        // 关系清零 + 账号软删留痕（行仍在库）
        Long orgRows = db.sql("SELECT COUNT(*)::int AS c FROM organization_membership"
                        + " WHERE organization_id = CAST(:org AS uuid) AND account_id = CAST(:acct AS uuid)")
                .bind("org", orgId).bind("acct", staffId)
                .map(r -> r.get("c", Integer.class)).one().block().longValue();
        Long storeRows = db.sql("SELECT COUNT(*)::int AS c FROM store_membership"
                        + " WHERE account_id = CAST(:acct AS uuid) AND store_id = CAST(:store AS uuid)")
                .bind("acct", staffId).bind("store", storeId)
                .map(r -> r.get("c", Integer.class)).one().block().longValue();
        assertThat(orgRows).isZero();
        assertThat(storeRows).isZero();
        assertThat(statusOf(staffId)).isEqualTo("deleted");
        String deletedAt = db.sql("SELECT deleted_at::text FROM app_users WHERE id = CAST(:id AS uuid)")
                .bind("id", staffId).map(r -> r.get(0, String.class)).one().block();
        assertThat(deletedAt).isNotBlank();

        // 终态：restore 409（D8 拍板：删除不可恢复）+ 重删 409（终态预检先于关系守卫）
        restore(orgId, staffId, cookie).expectStatus().isEqualTo(409)
                .expectBody().jsonPath("$.error").isEqualTo("账号已删除，不可恢复");
        client().delete().uri("/api/organizations/" + orgId + "/accounts/" + staffId)
                .header("Cookie", "y1.sid=" + cookie).exchange().expectStatus().isEqualTo(409)
                .expectBody().jsonPath("$.error").isEqualTo("账号已删除，不可重复删除");

        // 事件落 outbox
        Long events = db.sql("SELECT COUNT(*)::int AS c FROM outbox"
                        + " WHERE event_type = 'OrgSubAccountDeleted' AND payload->>'accountId' = :acct")
                .bind("acct", staffId)
                .map(r -> r.get("c", Integer.class)).one().block().longValue();
        assertThat(events).isEqualTo(1);
    }

    @Test
    void deleteSubAccount_guards_selfAndOwner_soleManagerDeletable() {
        var owner = seedAccount("sa-delg@example.com");
        String cookie = owner.cookie();
        String orgId = createOrg(cookie, "删守卫主体");
        String storeId = createStore(orgId, cookie, "独店");

        // 自己不可删；owner 不可被他人删
        client().delete().uri("/api/organizations/" + orgId + "/accounts/" + owner.accountId())
                .header("Cookie", "y1.sid=" + cookie).exchange().expectStatus().isForbidden();

        // 决策 E：店内唯一经理可删（D8① 已废除），删除后关系清零
        Map<String, Object> mgr = createAccount(orgId, cookie, managerJson(storeId, "onlydel", "唯一经理"))
                .expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();
        String mgrId = (String) ((Map<?, ?>) ((Map<?, ?>) mgr.get("data")).get("account")).get("id");
        client().delete().uri("/api/organizations/" + orgId + "/accounts/" + mgrId)
                .header("Cookie", "y1.sid=" + cookie).exchange().expectStatus().isOk();
        Long storeRows = db.sql("SELECT COUNT(*)::int AS c FROM store_membership"
                        + " WHERE account_id = CAST(:acct AS uuid)")
                .bind("acct", mgrId)
                .map(r -> r.get("c", Integer.class)).one().block().longValue();
        assertThat(storeRows).isZero();
    }

    // ---------- helpers ----------

    private org.springframework.test.web.reactive.server.WebTestClient.ResponseSpec createAccount(
            String orgId, String cookie, String json) {
        return client().post().uri("/api/organizations/" + orgId + "/accounts")
                .contentType(MediaType.APPLICATION_JSON).header("Cookie", "y1.sid=" + cookie)
                .bodyValue(json).exchange();
    }

    private String managerJson(String storeId, String loginName, String displayName) {
        return "{\"role\":\"manager\",\"storeId\":\"" + storeId + "\",\"loginName\":\"" + loginName
                + "\",\"displayName\":\"" + displayName + "\"}";
    }

    private String staffJson(String storeId, String loginName, String displayName) {
        return "{\"role\":\"staff\",\"storeId\":\"" + storeId + "\",\"loginName\":\"" + loginName
                + "\",\"displayName\":\"" + displayName + "\"}";
    }

    /**
     * #49：任命经理唯一通路 = 主体直建（org 入口 role=manager+storeId）。
     * 返回带登录态的子账号（cookieFor 把任意 accountId 转登录态）。
     */
    @SuppressWarnings("unchecked")
    private Seeded createManagerViaOrg(String orgId, String storeId, String ownerCookie,
            String loginName, String displayName) {
        Map<String, Object> data = createAccount(orgId, ownerCookie,
                managerJson(storeId, loginName, displayName))
                .expectStatus().isCreated().expectBody(Map.class).returnResult().getResponseBody();
        String accountId = (String) ((Map<String, Object>) ((Map<String, Object>) data.get("data")).get("account"))
                .get("id");
        return new Seeded(cookieFor(accountId), accountId);
    }

    /** 挂靠端点已下线（#49），组织角色用 SQL 直插（IT 造数，非业务通路）。 */
    private void seedOrgRole(String orgId, String accountId, String role) {
        db.sql("INSERT INTO organization_membership(id, organization_id, account_id, role)"
                        + " VALUES (gen_random_uuid(), CAST(:org AS uuid), CAST(:acct AS uuid), :role)")
                .bind("org", orgId).bind("acct", accountId).bind("role", role).then().block();
    }

    private org.springframework.test.web.reactive.server.WebTestClient.ResponseSpec suspend(
            String orgId, String accountId, String cookie) {
        return client().post()
                .uri("/api/organizations/" + orgId + "/accounts/" + accountId + "/suspend")
                .header("Cookie", "y1.sid=" + cookie).exchange();
    }

    private org.springframework.test.web.reactive.server.WebTestClient.ResponseSpec restore(
            String orgId, String accountId, String cookie) {
        return client().post()
                .uri("/api/organizations/" + orgId + "/accounts/" + accountId + "/restore")
                .header("Cookie", "y1.sid=" + cookie).exchange();
    }

    private String accountPrefix(String orgId) {
        return db.sql("SELECT account_prefix FROM organization WHERE id = CAST(:id AS uuid)")
                .bind("id", orgId).map(r -> r.get("account_prefix", String.class)).one().block();
    }

    private String statusOf(String accountId) {
        return db.sql("SELECT status FROM app_users WHERE id = CAST(:id AS uuid)")
                .bind("id", accountId)
                .map(r -> r.get("status", String.class)).one().block();
    }
}
