/**
 * 视频剪辑模板库（任务书 #43 Stage 3）。
 *
 * 静态常量 ≥10 个，覆盖：抖音口播 / 抖音剧情种草 / 小红书探店 vlog / 美食制作 /
 * 产品开箱 / 对比测评 / 教程清单 / 朋友圈好物 / 点评图文轮播 / 公众号头图封面。
 */
import type { VideoEditTemplate } from '../types/grassland/ai-studio'

export const VIDEO_EDIT_TEMPLATES: ReadonlyArray<VideoEditTemplate> = [
  {
    id: 'douyin-talk',
    name: '抖音口播',
    platforms: ['douyin'],
    forms: ['talking-head'],
    pace: 'fast',
    durationHint: '30–60s',
    structure: [
      { beat: 'hook', timeShare: 0.1, hint: '前 3 秒抓注意力：提问/冲突/数字' },
      { beat: 'pain', timeShare: 0.2, hint: '痛点共鸣：描述目标受众的困扰' },
      { beat: 'solution', timeShare: 0.35, hint: '解决方案：核心观点/方法' },
      { beat: 'proof', timeShare: 0.2, hint: '证据/案例/数据' },
      { beat: 'cta', timeShare: 0.15, hint: '行动号召：关注/评论/收藏' },
    ],
    subtitleStyle: '居中大字描边',
    bgmMood: 'energetic',
  },
  {
    id: 'douyin-drama',
    name: '抖音剧情种草',
    platforms: ['douyin'],
    forms: ['story', 'review'],
    pace: 'medium',
    durationHint: '60–90s',
    structure: [
      { beat: 'scene', timeShare: 0.15, hint: '场景建立：日常情境引入' },
      { beat: 'conflict', timeShare: 0.2, hint: '冲突/转折：制造戏剧张力' },
      { beat: 'product', timeShare: 0.3, hint: '产品出场：自然植入' },
      { beat: 'effect', timeShare: 0.2, hint: '效果展示：前后对比' },
      { beat: 'ending', timeShare: 0.15, hint: '收尾：反转/金句/引导互动' },
    ],
    subtitleStyle: '左下大字描边',
    bgmMood: 'playful',
  },
  {
    id: 'xhs-vlog',
    name: '小红书探店 Vlog',
    platforms: ['xiaohongshu'],
    forms: ['vlog', 'review'],
    pace: 'medium',
    durationHint: '60–120s',
    structure: [
      { beat: 'intro', timeShare: 0.1, hint: '地点/氛围展示' },
      { beat: 'first-impression', timeShare: 0.2, hint: '第一印象：环境/服务' },
      { beat: 'highlight', timeShare: 0.35, hint: '亮点推荐：招牌/特色' },
      { beat: 'detail', timeShare: 0.2, hint: '细节：价格/位置/贴士' },
      { beat: 'summary', timeShare: 0.15, hint: '总结评分+推荐语' },
    ],
    subtitleStyle: '居中大字色块底',
    bgmMood: 'relaxed',
  },
  {
    id: 'food-making',
    name: '美食制作',
    platforms: ['douyin', 'xiaohongshu'],
    forms: ['tutorial'],
    pace: 'medium',
    durationHint: '60–180s',
    structure: [
      { beat: 'result', timeShare: 0.1, hint: '成品展示（倒叙钩子）' },
      { beat: 'ingredients', timeShare: 0.15, hint: '食材清单' },
      { beat: 'prep', timeShare: 0.2, hint: '备料过程' },
      { beat: 'cooking', timeShare: 0.35, hint: '烹饪步骤（核心）' },
      { beat: 'plating', timeShare: 0.1, hint: '装盘/点缀' },
      { beat: 'taste', timeShare: 0.1, hint: '试吃/点评' },
    ],
    subtitleStyle: '左下大字描边',
    bgmMood: 'warm',
  },
  {
    id: 'unboxing',
    name: '产品开箱',
    platforms: ['douyin', 'xiaohongshu'],
    forms: ['review', 'unboxing'],
    pace: 'medium',
    durationHint: '60–120s',
    structure: [
      { beat: 'tease', timeShare: 0.1, hint: '悬念引入：这是什么？' },
      { beat: 'package', timeShare: 0.2, hint: '外包装/开箱体验' },
      { beat: 'first-look', timeShare: 0.2, hint: '第一印象/外观细节' },
      { beat: 'features', timeShare: 0.3, hint: '功能/卖点演示' },
      { beat: 'verdict', timeShare: 0.2, hint: '总结/值不值得买' },
    ],
    subtitleStyle: '居中大字描边',
    bgmMood: 'curious',
  },
  {
    id: 'comparison',
    name: '对比测评',
    platforms: ['douyin', 'bilibili'],
    forms: ['review'],
    pace: 'medium',
    durationHint: '90–180s',
    structure: [
      { beat: 'question', timeShare: 0.1, hint: '核心问题：选哪个？' },
      { beat: 'candidates', timeShare: 0.15, hint: '选手介绍' },
      { beat: 'round1', timeShare: 0.25, hint: '对比维度 1' },
      { beat: 'round2', timeShare: 0.25, hint: '对比维度 2' },
      { beat: 'round3', timeShare: 0.15, hint: '对比维度 3' },
      { beat: 'conclusion', timeShare: 0.1, hint: '结论/推荐' },
    ],
    subtitleStyle: '居中大字色块底',
    bgmMood: 'analytical',
  },
  {
    id: 'tutorial-list',
    name: '教程清单',
    platforms: ['douyin', 'xiaohongshu', 'bilibili'],
    forms: ['tutorial'],
    pace: 'slow',
    durationHint: '60–120s',
    structure: [
      { beat: 'intro', timeShare: 0.1, hint: '今天要教什么' },
      { beat: 'step1', timeShare: 0.25, hint: '步骤 1' },
      { beat: 'step2', timeShare: 0.25, hint: '步骤 2' },
      { beat: 'step3', timeShare: 0.25, hint: '步骤 3' },
      { beat: 'recap', timeShare: 0.15, hint: '总结回顾' },
    ],
    subtitleStyle: '左下大字描边',
    bgmMood: 'calm',
  },
  {
    id: 'wechat-moment',
    name: '朋友圈好物',
    platforms: ['wechat'],
    forms: ['review'],
    pace: 'slow',
    durationHint: '15–30s',
    structure: [
      { beat: 'beauty-shot', timeShare: 0.4, hint: '精美产品镜头' },
      { beat: 'use-case', timeShare: 0.3, hint: '使用场景' },
      { beat: 'text-overlay', timeShare: 0.3, hint: '文字+价格信息' },
    ],
    subtitleStyle: '居中大字色块底',
    bgmMood: 'cozy',
  },
  {
    id: 'dianping-carousel',
    name: '点评图文轮播',
    platforms: ['dianping'],
    forms: ['image-carousel'],
    pace: 'slow',
    durationHint: '6–9 张图',
    structure: [
      { beat: 'cover', timeShare: 0.15, hint: '封面图：最吸睛的一张' },
      { beat: 'environment', timeShare: 0.2, hint: '环境/氛围' },
      { beat: 'product-1', timeShare: 0.2, hint: '推荐项 1' },
      { beat: 'product-2', timeShare: 0.2, hint: '推荐项 2' },
      { beat: 'info', timeShare: 0.15, hint: '地址/价格/贴士' },
      { beat: 'cta', timeShare: 0.1, hint: '收藏/打卡引导' },
    ],
    subtitleStyle: '居中大字色块底',
    bgmMood: 'relaxed',
  },
  {
    id: 'wechat-cover',
    name: '公众号头图封面',
    platforms: ['wechat'],
    forms: ['article-cover'],
    pace: 'slow',
    durationHint: '单图',
    structure: [
      { beat: 'hero', timeShare: 0.5, hint: '主视觉：高对比度大图' },
      { beat: 'title', timeShare: 0.3, hint: '标题文字：≤12 字' },
      { beat: 'brand', timeShare: 0.2, hint: '品牌标识/Logo 角标' },
    ],
    subtitleStyle: '居中大字色块底',
    bgmMood: '',
  },
]
