// image-operations.test.ts — C107-06 (task-107) real OpenCV transforms (K08).
//
// Real pixel truth: a solid-color PNG generated by the managed interpreter is
// transformed/composed through the upstream raster_execute.py, then decoded
// back through the same interpreter — dims, channels, and sample pixels are
// asserted, not just output bytes existing. Requires the frozen image.opencv
// environment (uv sync; programs.test.ts prepares the same stable root).
import { strict as assert } from "node:assert";
import { execFile } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import test from "node:test";

import { runImageTool } from "../../src/tools/image.ts";
import { PROGRAM_CATALOG } from "../../src/programs/catalog.ts";
import { opencvProbe } from "../../src/programs/health.ts";
import { openHandleRegistry, registerResource, resolveResource } from "../../src/resources/handles.ts";
import { CommandStore } from "../../src/commands/store.ts";

const execFileAsync = promisify(execFile);
const repoRoot = join(import.meta.dirname, "../../../..");
const distributionRoot = join(repoRoot, "platform-hypit/.generated/hypit");
const programsRoot = join(repoRoot, "test-artifacts/task-107/C06/programs");
const python = PROGRAM_CATALOG["image.opencv.local"].pythonExecutable(programsRoot);

/** Decode through the managed interpreter: {width, height, channels, bgra sample}. */
async function decode(path: string): Promise<{ width: number; height: number; channels: number; center: number[] }> {
  const script = [
    "import cv2, numpy, json, sys",
    `image = cv2.imread(sys.argv[1], cv2.IMREAD_UNCHANGED)`,
    "h, w = image.shape[:2]",
    "c = image.shape[2] if image.ndim == 3 else 1",
    "y, x = h // 2, w // 2",
    "pixel = [int(v) for v in (image[y, x] if c == 1 else image[y, x])]",
    "print(json.dumps({'width': w, 'height': h, 'channels': c, 'center': pixel[:4]}))",
  ].join("\n");
  const { stdout } = await execFileAsync(python, ["-c", script, path], { timeout: 30_000 });
  return JSON.parse(stdout.trim()) as { width: number; height: number; channels: number; center: number[] };
}

/** Encode a solid-color PNG with the managed interpreter (no host image deps). */
async function solidPng(path: string, width: number, height: number, bgra: number[]): Promise<void> {
  const script = [
    "import cv2, numpy as np, sys",
    "w, h = int(sys.argv[2]), int(sys.argv[3])",
    "color = np.array([int(v) for v in sys.argv[4].split(',')], dtype=np.uint8)",
    "image = np.empty((h, w, len(color)), dtype=np.uint8); image[:] = color",
    "ok = cv2.imwrite(sys.argv[1], image)",
    "sys.exit(0 if ok else 1)",
  ].join("\n");
  await execFileAsync(python, ["-c", script, path, String(width), String(height), bgra.join(",")], { timeout: 30_000 });
}

type Fixture = { readonly scratch: string; readonly sourcePath: string; readonly store: CommandStore; readonly registryRoot: string };

async function readyOrSkip(t: test.TestContext): Promise<Fixture | undefined> {
  const probe = await opencvProbe(PROGRAM_CATALOG["image.opencv.local"], programsRoot);
  if (probe.state !== "ready") {
    t.skip(`image.opencv.local not prepared (${probe.detail ?? "probe failed"}): run deploy/hypit/prepare-programs.sh or programs prepare first (live dependency)`);
    return undefined;
  }
  const scratch = mkdtempSync(join(tmpdir(), "hypit-image-test-"));
  const registryRoot = join(scratch, "resources");
  mkdirSync(registryRoot, { recursive: true });
  const sourcePath = join(scratch, "source.png");
  await solidPng(sourcePath, 64, 48, [40, 80, 200, 255]);
  const store = new CommandStore(join(scratch, "bridge.sqlite"));
  return { scratch, sourcePath, store, registryRoot };
}

test("image.transform: crop + rotate 90 + encode through real OpenCV", { timeout: 60_000 }, async (t) => {
  const fixture = await readyOrSkip(t);
  if (fixture === undefined) return;
  try {
    const registry = openHandleRegistry([fixture.registryRoot], join(fixture.registryRoot, "handles.index.json"), fixture.store);
    const result = await runImageTool("image.transform", {
      operations: [
        { kind: "crop", unit: "px", x: 0, y: 0, width: 64, height: 32 },
        { kind: "rotate", degrees: 90 },
        { kind: "encode", format: "png" },
      ],
      __sourcePath: fixture.sourcePath,
    } as unknown as Record<string, unknown>, {
      registry,
      programsRoot,
      distributionRoot,
      resolveSource: async (payload) => String(payload.__sourcePath),
    });
    assert.match(String(result.handle), /^res-[0-9a-f]{16}-[0-9a-z]+$/u);
    assert.equal(result.mediaType, "image/png");
    // 64x32 rotated 90° becomes 32x64; center stays the solid color.
    const artifact = await resolveResource(registry, String(result.handle));
    const decoded = await decode(artifact.absolutePath);
    assert.equal(decoded.width, 32);
    assert.equal(decoded.height, 64);
    assert.deepEqual(decoded.center, [40, 80, 200, 255]);
  } finally {
    rmSync(fixture.scratch, { recursive: true, force: true });
  }
});

test("image.transform: alpha flatten loses the alpha channel; resize interpolates geometry", { timeout: 60_000 }, async (t) => {
  const fixture = await readyOrSkip(t);
  if (fixture === undefined) return;
  try {
    const registry = openHandleRegistry([fixture.registryRoot], join(fixture.registryRoot, "handles.index.json"), fixture.store);
    const result = await runImageTool("image.transform", {
      operations: [
        { kind: "alpha", mode: "flatten", background: "#101010" },
        { kind: "resize", width: 32, height: 24, fit: "stretch", interpolation: "linear" },
        { kind: "encode", format: "jpeg" },
      ],
      __sourcePath: fixture.sourcePath,
    } as unknown as Record<string, unknown>, {
      registry,
      programsRoot,
      distributionRoot,
      resolveSource: async (payload) => String(payload.__sourcePath),
    });
    assert.equal(result.mediaType, "image/jpeg");
    const artifact = await resolveResource(registry, String(result.handle));
    const decoded = await decode(artifact.absolutePath);
    assert.equal(decoded.width, 32);
    assert.equal(decoded.height, 24);
    assert.equal(decoded.channels, 3, "flattened JPEG has no alpha channel");
    // Solid blue stays blue after flatten; JPEG is lossy so allow a re-encode step.
    assert.ok(Math.abs(decoded.center[0]! - 40) <= 3, `blue B survives flatten within JPEG tolerance: ${String(decoded.center[0])}`);
    assert.ok(Math.abs(decoded.center[2]! - 200) <= 3, `blue R survives flatten within JPEG tolerance: ${String(decoded.center[2])}`);
  } finally {
    rmSync(fixture.scratch, { recursive: true, force: true });
  }
});

test("image.compose: two layers over a canvas through real OpenCV", { timeout: 60_000 }, async (t) => {
  const fixture = await readyOrSkip(t);
  if (fixture === undefined) return;
  try {
    const registry = openHandleRegistry([fixture.registryRoot], join(fixture.registryRoot, "handles.index.json"), fixture.store);
    // Layers reference registered resources the same way the dispatcher wire does;
    // registered paths must live inside the registry's allowed roots.
    const bluePath = join(fixture.registryRoot, "source.png");
    copyFileSync(fixture.sourcePath, bluePath);
    const redPath = join(fixture.registryRoot, "red.png");
    await solidPng(redPath, 16, 16, [0, 0, 220, 255]);
    const blueSource = await registerResource(registry, { absolutePath: bluePath, projectId: null, mediaType: "image/png", role: "image-tool-source" });
    const redSource = await registerResource(registry, { absolutePath: redPath, projectId: null, mediaType: "image/png", role: "image-tool-source" });
    const result = await runImageTool("image.compose", {
      canvas: { widthPx: 64, heightPx: 64 },
      background: "#ffffff",
      layers: [
        { source: { handle: blueSource.handle }, frame: { xPx: 0, yPx: 0, widthPx: 32, heightPx: 32 }, fit: "stretch", interpolation: "nearest", opacity: 1 },
        { source: { handle: redSource.handle }, frame: { xPx: 32, yPx: 32, widthPx: 32, heightPx: 32 }, fit: "stretch", interpolation: "nearest", opacity: 1 },
      ],
    } as unknown as Record<string, unknown>, {
      registry,
      programsRoot,
      distributionRoot,
      resolveSource: async (payload) => {
        if (typeof payload.handle === "string") {
          return (await resolveResource(registry, payload.handle)).absolutePath;
        }
        throw new Error("test resolveSource expects {handle}");
      },
    });
    assert.match(String(result.handle), /^res-[0-9a-f]{16}-[0-9a-z]+$/u);
    const artifact = await resolveResource(registry, String(result.handle));
    const script = [
      "import cv2, numpy, json, sys",
      "image = cv2.imread(sys.argv[1], cv2.IMREAD_UNCHANGED)",
      "def px(x, y): return [int(v) for v in image[y, x][:3]]",
      "print(json.dumps({'tl': px(8, 8), 'br': px(56, 56), 'bg': px(48, 16)}))",
    ].join("\n");
    const { stdout } = await execFileAsync(python, ["-c", script, artifact.absolutePath], { timeout: 30_000 });
    const samples = JSON.parse(stdout.trim()) as { tl: number[]; br: number[]; bg: number[] };
    assert.deepEqual(samples.tl, [40, 80, 200], "top-left quadrant shows the blue layer");
    assert.deepEqual(samples.br, [0, 0, 220], "bottom-right quadrant shows the red layer");
    assert.deepEqual(samples.bg, [255, 255, 255], "uncovered top-right quadrant keeps the background");
  } finally {
    rmSync(fixture.scratch, { recursive: true, force: true });
  }
});

test("image.transform: unknown operations are rejected before any Python runs", async () => {
  const scratch = mkdtempSync(join(tmpdir(), "hypit-image-test-"));
  try {
    const registryRoot = join(scratch, "resources");
    mkdirSync(registryRoot, { recursive: true });
    const registry = openHandleRegistry([registryRoot], join(registryRoot, "handles.index.json"), new CommandStore(join(scratch, "bridge.sqlite")));
    writeFileSync(join(scratch, "x.png"), new Uint8Array([1]), "binary");
    await assert.rejects(
      () => runImageTool("image.transform", {
        operations: [{ kind: "exfiltrate" }],
        __sourcePath: join(scratch, "x.png"),
      } as unknown as Record<string, unknown>, {
        registry,
        programsRoot,
        distributionRoot,
        resolveSource: async (payload) => String(payload.__sourcePath),
      }),
      (error: unknown) => (error as { code?: string }).code === "invalid_input",
      "the op vocabulary stays the upstream set",
    );
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
});
