/**
 * C107-14 knowledge/index.ts — broker-side knowledge index reader over
 * platform-hypit/knowledge/index.json (generated by knowledge/build-index.mjs
 * from the frozen upstream Skill documents). Hash-verified read, topic/keyword
 * search with snippets — same rules as the Java side.
 */
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DispatchError } from "../commands/dispatcher.ts";

type IndexEntry = {
  readonly path: string;
  readonly sha256: string;
  readonly title: string;
  readonly topic: string;
  readonly sourceCommit: string;
};

type KnowledgeIndex = {
  readonly format: string;
  readonly sourceRoot: string;
  readonly sourceCommit: string;
  readonly documents: readonly IndexEntry[];
};

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");
const indexRoot = resolve(repoRoot, "platform-hypit/knowledge");
const sourceRoot = resolve(repoRoot, "platform-hypit/.generated/hypit/skills/hypit");

let cached: KnowledgeIndex | undefined;

async function loadIndex(): Promise<KnowledgeIndex> {
  if (cached !== undefined) return cached;
  cached = JSON.parse(await readFile(resolve(indexRoot, "index.json"), "utf8")) as KnowledgeIndex;
  return cached;
}

export async function searchKnowledge(input: {
  topic?: string;
  query?: string;
  limit?: number;
}): Promise<unknown> {
  const index = await loadIndex();
  const needle = (input.query ?? "").toLowerCase();
  const limit = Math.min(Math.max(input.limit ?? 10, 1), 50);
  const hits = [];
  for (const entry of index.documents) {
    if (input.topic !== undefined && entry.topic !== input.topic) continue;
    let snippet: string | undefined;
    if (needle !== "" && !entry.title.toLowerCase().includes(needle)
      && !entry.path.toLowerCase().includes(needle)) {
      const text = (await readFile(resolve(sourceRoot, entry.path), "utf8")).toLowerCase();
      const at = text.indexOf(needle);
      if (at < 0) continue;
      snippet = text.slice(Math.max(0, at - 40), at + needle.length + 160);
    }
    hits.push({
      path: entry.path,
      title: entry.title,
      topic: entry.topic,
      ...(snippet === undefined ? {} : { snippet }),
    });
    if (hits.length >= limit) break;
  }
  return { hits, documentCount: index.documents.length, sourceCommit: index.sourceCommit };
}

export async function readKnowledge(path: string): Promise<unknown> {
  const index = await loadIndex();
  const entry = index.documents.find((candidate) => candidate.path === path);
  if (entry === undefined) {
    throw new DispatchError("not_found", `knowledge document not in index: ${path}`);
  }
  const text = await readFile(resolve(sourceRoot, entry.path), "utf8");
  const actual = createHash("sha256").update(text, "utf8").digest("hex");
  if (actual !== entry.sha256) {
    throw new DispatchError("knowledge_drift", `document drifted from index: ${path}`);
  }
  return { path, document: text, sha256: actual, sourceCommit: index.sourceCommit };
}
